# Generated by Django 5.2.11 on 2026-05-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=40)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_semanais', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('fabricante', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=100, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('placa', models.CharField(max_length=7)),
                ('modelo', models.CharField(max_length=80)),
                ('cor', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('quilometragem', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mecanica.cliente')),
            ],
            options={
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='ConsultorTecnico',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mecanica.funcionario')),
            ],
            bases=('mecanica.funcionario',),
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mecanica.funcionario')),
                ('especialidade', models.CharField(max_length=40, null=True)),
            ],
            options={
                'ordering': ['especialidade'],
            },
            bases=('mecanica.funcionario',),
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('previsao_termino', models.DateTimeField(null=True)),
                ('data_termino', models.DateTimeField(null=True)),
                ('descricao', models.CharField(max_length=100, null=True)),
                ('observacao', models.CharField(max_length=200, null=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mecanica.carro')),
                ('servicos', models.ManyToManyField(to='mecanica.servico')),
                ('consultorTecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mecanica.consultortecnico')),
                ('mecanicos', models.ManyToManyField(to='mecanica.mecanico')),
            ],
            options={
                'verbose_name_plural': 'OrdensServico',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='OrdemPecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mecanica.ordemservico')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mecanica.peca')),
            ],
            options={
                'verbose_name_plural': 'OrdensPecas',
                'ordering': ['ordem_servico'],
            },
        ),
    ]
