# Generated by Django 5.2.11 on 2026-05-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mecanico',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='especialidade',
        ),
    ]
