# Generated by Django 5.2.11 on 2026-05-08 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0002_alter_mecanico_options_remove_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultortecnico',
            options={'ordering': ['nome']},
        ),
    ]
