# Generated by Django 5.2.11 on 2026-05-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0003_alter_consultortecnico_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='consultorTecnico',
            new_name='consultor_tecnico',
        ),
    ]
