# Generated by Django 5.2.11 on 2026-08-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0004_rename_consultortecnico_ordemservico_consultor_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='previsao_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peca',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
