# Generated by Django 5.2.11 on 2026-08-28 03:08

import django.db.models.deletion
from django.db import migrations, models


def copiar_servicos_existentes(apps, schema_editor):
    OrdemServicoServico = apps.get_model('mecanica', 'OrdemServicoServico')
    Servico = apps.get_model('mecanica', 'Servico')
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        cursor.execute(
            'SELECT ordemservico_id, servico_id '
            'FROM mecanica_ordemservico_servicos'
        )
        vinculos = cursor.fetchall()

    precos = dict(Servico.objects.filter(
        id__in={servico_id for _, servico_id in vinculos}
    ).values_list('id', 'preco'))
    OrdemServicoServico.objects.bulk_create([
        OrdemServicoServico(
            ordem_servico_id=ordem_id,
            servico_id=servico_id,
            preco_unitario=precos[servico_id],
        )
        for ordem_id, servico_id in vinculos
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('mecanica', '0005_alter_ordemservico_data_termino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(
                    decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='ordempecas',
            old_name='preco',
            new_name='preco_unitario',
        ),
        migrations.AddConstraint(
            model_name='ordempecas',
            constraint=models.UniqueConstraint(
                fields=('ordem_servico', 'peca'), name='unique_peca_por_ordem'),
        ),
        migrations.AddField(
            model_name='ordemservicoservico',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ordem_servico_servicos', to='mecanica.ordemservico'),
        ),
        migrations.AddField(
            model_name='ordemservicoservico',
            name='servico',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='mecanica.servico'),
        ),
        migrations.RunPython(copiar_servicos_existentes,
                             migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='ordemservico',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='servicos',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='servicos',
            field=models.ManyToManyField(
                through='mecanica.OrdemServicoServico', to='mecanica.servico'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicoservico',
            constraint=models.UniqueConstraint(
                fields=('ordem_servico', 'servico'), name='unique_servico_por_ordem'),
        ),
    ]
