# Generated by Django 5.2.11 on 2026-08-28 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanica', '0006_ordemservicoservico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordempecas',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordem_pecas', to='mecanica.ordemservico'),
        ),
    ]
