
from django.urls import path
from .views import (
    ClienteCreate, ClienteUpdate, ClienteDelete, ClienteList, ClienteDetail,
    CarroCreate, CarroUpdate, CarroDelete, CarroList, CarroDetail,
    ServicoCreate, ServicoUpdate, ServicoDelete, ServicoList, ServicoDetail,
    PecaCreate, PecaUpdate, PecaDelete, PecaList, PecaDetail,
    FuncionarioCreate, FuncionarioUpdate, FuncionarioDelete, FuncionarioList, FuncionarioDetail,
    MecanicoCreate, MecanicoUpdate, MecanicoDelete, MecanicoList, MecanicoDetail,
    ConsultorTecnicoCreate, ConsultorTecnicoUpdate, ConsultorTecnicoDelete, ConsultorTecnicoList, ConsultorTecnicoDetail,
    OrdemServicoCreate, OrdemServicoUpdate, OrdemServicoDelete, OrdemServicoList, OrdemServicoDetail,
    OrdemPecasCreate, OrdemPecasUpdate, OrdemPecasDelete, OrdemPecasList, OrdemPecasDetail
)

urlpatterns = [
    path('cadastrar/cliente/', ClienteCreate.as_view(), name='cliente-create'),
    path('atualizar/cliente/<int:pk>/',
         ClienteUpdate.as_view(), name='cliente-update'),
    path('excluir/cliente/<int:pk>/',
         ClienteDelete.as_view(), name='cliente-delete'),
    path('listar/cliente/', ClienteList.as_view(), name='cliente-list'),
    path('detalhar/cliente/<int:pk>/',
         ClienteDetail.as_view(), name='cliente-detail'),

    path('cadastrar/carro/', CarroCreate.as_view(), name='carro-create'),
    path('atualizar/carro/<int:pk>/', CarroUpdate.as_view(), name='carro-update'),
    path('excluir/carro/<int:pk>/', CarroDelete.as_view(), name='carro-delete'),
    path('listar/carro/', CarroList.as_view(), name='carro-list'),
    path('detalhar/carro/<int:pk>/', CarroDetail.as_view(), name='carro-detail'),

    path('cadastrar/servico/', ServicoCreate.as_view(), name='servico-create'),
    path('atualizar/servico/<int:pk>/',
         ServicoUpdate.as_view(), name='servico-update'),
    path('excluir/servico/<int:pk>/',
         ServicoDelete.as_view(), name='servico-delete'),
    path('listar/servico/', ServicoList.as_view(), name='servico-list'),
    path('detalhar/servico/<int:pk>/',
         ServicoDetail.as_view(), name='servico-detail'),

    path('cadastrar/peca/', PecaCreate.as_view(), name='peca-create'),
    path('atualizar/peca/<int:pk>/', PecaUpdate.as_view(), name='peca-update'),
    path('excluir/peca/<int:pk>/', PecaDelete.as_view(), name='peca-delete'),
    path('listar/peca/', PecaList.as_view(), name='peca-list'),
    path('detalhar/peca/<int:pk>/', PecaDetail.as_view(), name='peca-detail'),

    path('cadastrar/funcionario/', FuncionarioCreate.as_view(),
         name='funcionario-create'),
    path('atualizar/funcionario/<int:pk>/',
         FuncionarioUpdate.as_view(), name='funcionario-update'),
    path('excluir/funcionario/<int:pk>/',
         FuncionarioDelete.as_view(), name='funcionario-delete'),
    path('listar/funcionario/', FuncionarioList.as_view(), name='funcionario-list'),
    path('detalhar/funcionario/<int:pk>/',
         FuncionarioDetail.as_view(), name='funcionario-detail'),

    path('cadastrar/mecanico/', MecanicoCreate.as_view(), name='mecanico-create'),
    path('atualizar/mecanico/<int:pk>/',
         MecanicoUpdate.as_view(), name='mecanico-update'),
    path('excluir/mecanico/<int:pk>/',
         MecanicoDelete.as_view(), name='mecanico-delete'),
    path('listar/mecanico/', MecanicoList.as_view(), name='mecanico-list'),
    path('detalhar/mecanico/<int:pk>/',
         MecanicoDetail.as_view(), name='mecanico-detail'),

    path('cadastrar/consultor-tecnico/',
         ConsultorTecnicoCreate.as_view(), name='consultor-tecnico-create'),
    path('atualizar/consultor-tecnico/<int:pk>/',
         ConsultorTecnicoUpdate.as_view(), name='consultor-tecnico-update'),
    path('excluir/consultor-tecnico/<int:pk>/',
         ConsultorTecnicoDelete.as_view(), name='consultor-tecnico-delete'),
    path('listar/consultor-tecnico/',
         ConsultorTecnicoList.as_view(), name='consultor-tecnico-list'),
    path('detalhar/consultor-tecnico/<int:pk>/',
         ConsultorTecnicoDetail.as_view(), name='consultor-tecnico-detail'),

    path('cadastrar/ordem-servico/',
         OrdemServicoCreate.as_view(), name='ordem-servico-create'),
    path('atualizar/ordem-servico/<int:pk>/',
         OrdemServicoUpdate.as_view(), name='ordem-servico-update'),
    path('excluir/ordem-servico/<int:pk>/',
         OrdemServicoDelete.as_view(), name='ordem-servico-delete'),
    path('listar/ordem-servico/', OrdemServicoList.as_view(),
         name='ordem-servico-list'),
    path('detalhar/ordem-servico/<int:pk>/',
         OrdemServicoDetail.as_view(), name='ordem-servico-detail'),

    path('cadastrar/ordem-pecas/', OrdemPecasCreate.as_view(),
         name='ordem-pecas-create'),
    path('atualizar/ordem-pecas/<int:pk>/',
         OrdemPecasUpdate.as_view(), name='ordem-pecas-update'),
    path('excluir/ordem-pecas/<int:pk>/',
         OrdemPecasDelete.as_view(), name='ordem-pecas-delete'),
    path('listar/ordem-pecas/', OrdemPecasList.as_view(), name='ordem-pecas-list'),
    path('detalhar/ordem-pecas/<int:pk>/',
         OrdemPecasDetail.as_view(), name='ordem-pecas-detail'),
]
